name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: cargo fmt
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - name: install rustfmt
        run: rustup component add rustfmt

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test-stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    name: cargo clippy+test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true

      - name: cargo clippy image_ssd
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=Cargo.toml -- -D warnings

      - name: cargo test image_ssd
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=Cargo.toml --all-features

  test-nightly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    name: cargo test nightly
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: cargo test image_ssd
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=Cargo.toml
